export { default as AllProducts } from './AllProducts'
export { default as Amount } from './Amount'
export { default as AddProduct } from './AddProduct'
export { default as AllOrders } from './AllOrders'
export { default as AllCategories } from './AllCategories'
export { default as AllUsers } from './AllUsers'
export { default as Profile } from './Profile'
